import LegalPage, { contactEmail } from '@/components/LegalPage';

export default function Privacy() {
  const contact = contactEmail ? <a className="underline" href={`mailto:${contactEmail}`}>{contactEmail}</a> : 'the site owner';
  return (
    <LegalPage title="Privacy Policy">
      <p>ExpertPrompter turns your ideas into detailed AI prompts. This page explains what we store and why.</p>

      <h2>What we collect</h2>
      <ul>
        <li><strong>Account details:</strong> your email address, and your name and profile picture if you sign in with Google, Facebook or GitHub. We never receive your password for those services.</li>
        <li><strong>Your prompts:</strong> the ideas you type and the prompts we generate, saved to your history.</li>
        <li><strong>Files you attach:</strong> files are read in your browser. Only their text is sent to build your prompt, and the files themselves are never uploaded or stored. The text becomes part of the generated prompt, so it is saved in your history with that prompt.</li>
        <li><strong>Photos you attach:</strong> colours, light and shape are measured in your browser, and &ldquo;Describe with AI&rdquo; runs an AI model on your own device, so the photo is not uploaded. The model (about 215&nbsp;MB) is downloaded once from Hugging Face and the AI library from jsDelivr, and your browser caches them. Only the resulting text description is sent to build your prompt. (If the site owner switches on a server AI instead, a reduced copy of the photo goes to Google&apos;s Gemini or Anthropic&apos;s Claude API to be described.)</li>
        <li><strong>Usage:</strong> how many free prompts you have used.</li>
        <li><strong>Billing:</strong> if you subscribe, Stripe processes your payment. We store your subscription status, never your card details.</li>
      </ul>

      <h2>How we use it</h2>
      <p>Only to run the service: signing you in, showing your history, counting free prompts and managing your subscription. We do not sell your data or use it for advertising. Prompts are generated by our own rule-based code. Photos are described on your own device.</p>

      <h2>Service providers</h2>
      <p>Vercel hosts the app, Supabase stores the database, Stripe handles payments, and Hugging Face and jsDelivr deliver the on-device photo AI. Each processes data only to provide its service.</p>

      <h2>Deleting your data</h2>
      <p>You can delete individual prompts from your history at any time. To delete your whole account, including data received through Facebook, Google or GitHub sign-in, contact {contact} from the email on your account and we will delete it within 30 days. You can also remove ExpertPrompter from the connected apps in your Facebook, Google or GitHub settings.</p>

      <h2>Contact</h2>
      <p>Questions about privacy: {contact}.</p>
    </LegalPage>
  );
}
