import Foundation
import NocternalModel

/// Neon theme presets (generated from the Kotlin ThemePresets).
public enum ThemePresets {
    public static let sacredGoldAura = ThemePreset(id: "sacred_gold_aura", name: "Sacred Gold Aura", accent: "#FFC940", secondary: "#FF8A00", glow: 0.75, edge: .gradient, thickness: 5, brightness: 0.7, animation: .auroraRibbon, eq: "vocal_clarity", background: .sacredMandala)
    public static let emeraldTranquility = ThemePreset(id: "emerald_tranquility", name: "Emerald Tranquility", accent: "#00F5A0", secondary: "#00B37A", glow: 0.55, edge: .gradient, thickness: 4, brightness: 0.55, animation: .infinityLoop, eq: "airy_highs", background: .auroraHaze)
    public static let moonlitCyanDrift = ThemePreset(id: "moonlit_cyan_drift", name: "Moonlit Cyan Drift", accent: "#7FE7FF", secondary: "#3A6EA5", glow: 0.2, edge: .staticGlow, thickness: 2, brightness: 0.25, animation: .auroraRibbon, eq: "balanced_lows", background: .amoledBlack, mode: .amoled)
    public static let royalPurpleGold = ThemePreset(id: "royal_purple_gold", name: "Royal Purple Gold", accent: "#B14CFF", secondary: "#FFC940", glow: 0.7, edge: .gradient, thickness: 5, brightness: 0.75, animation: .prismCycle, eq: "warm_mids", background: .nebula)
    public static let electricBluePulse = ThemePreset(id: "electric_blue_pulse", name: "Electric Blue Pulse", accent: "#00A3FF", secondary: "#00FFF0", glow: 1, edge: .musicReactive, thickness: 6, brightness: 1, animation: .pulseWaveSpectrum, eq: "edm_punch", background: .gridHorizon)
    public static let violetHyperspace = ThemePreset(id: "violet_hyperspace", name: "Violet Hyperspace", accent: "#8F00FF", secondary: "#FF00E5", glow: 0.9, edge: .musicReactive, thickness: 5, brightness: 0.9, animation: .vortexSpiral, eq: "trance_wide", background: .starfield)
    public static let cyberRedPulse = ThemePreset(id: "cyber_red_pulse", name: "Cyber Red Pulse", accent: "#FF1744", secondary: "#FF6D00", glow: 1, edge: .musicReactive, thickness: 6, brightness: 1, animation: .bassShockFlash, eq: "techno_sub", background: .gridHorizon, mode: .amoled)
    public static let bluePurpleGalaxy = ThemePreset(id: "blue_purple_galaxy", name: "Blue-Purple Galaxy", accent: "#4D7CFF", secondary: "#A64DFF", glow: 0.8, edge: .gradient, thickness: 5, brightness: 0.8, animation: .hyperBeamEdgeFlow, eq: "night_drive", background: .nebula)
    public static let softPinkGlow = ThemePreset(id: "soft_pink_glow", name: "Soft Pink Glow", accent: "#FF8AD8", secondary: "#B388FF", glow: 0.45, edge: .staticGlow, thickness: 3, brightness: 0.5, animation: .eqBarMirage, eq: "lofi_warm", background: .rainGlass)
    public static let aquaDrift = ThemePreset(id: "aqua_drift", name: "Aqua Drift", accent: "#00E5D4", secondary: "#00A3FF", glow: 0.55, edge: .gradient, thickness: 4, brightness: 0.6, animation: .starfallReactive, eq: "chill_smooth", background: .auroraHaze)
    public static let deepSpaceIndigo = ThemePreset(id: "deep_space_indigo", name: "Deep Space Indigo", accent: "#5C6BFF", secondary: "#00E5FF", glow: 0.5, edge: .gradient, brightness: 0.5, animation: .crystalGrid, eq: "ambient_space", background: .starfield)
    public static let voltLimeSurge = ThemePreset(id: "volt_lime_surge", name: "Volt Lime Surge", accent: "#B6FF00", secondary: "#00FF85", glow: 1, edge: .musicReactive, thickness: 6, brightness: 1, animation: .bassShockFlash, eq: "workout_bass", background: .gridHorizon)
    public static let laserFocusTeal = ThemePreset(id: "laser_focus_teal", name: "Laser Focus Teal", accent: "#1DE9B6", secondary: "#80CBC4", glow: 0.3, edge: .staticGlow, thickness: 2, brightness: 0.35, animation: .eqBarMirage, eq: "focus_neutral", background: .deepSpace, mode: .dark)
    public static let roseNeonHeart = ThemePreset(id: "rose_neon_heart", name: "Rose Neon Heart", accent: "#FF2E88", secondary: "#FF8A80", glow: 0.7, edge: .gradient, brightness: 0.7, animation: .infinityLoop, eq: "romantic_warm", background: .softGlow)
    public static let rainbowRave = ThemePreset(id: "rainbow_rave", name: "Rainbow Rave", accent: "#FF00E5", secondary: "#00FFF0", glow: 1, edge: .musicReactive, thickness: 7, brightness: 1, animation: .pulseWaveSpectrum, eq: "party_loud", background: .gridHorizon)
    public static let sunriseAmber = ThemePreset(id: "sunrise_amber", name: "Sunrise Amber", accent: "#FFAB40", secondary: "#FF6E6E", glow: 0.6, edge: .gradient, brightness: 0.65, animation: .auroraRibbon, eq: "morning_bright", background: .softGlow, mode: .light)
    public static let silverStrings = ThemePreset(id: "silver_strings", name: "Silver Strings", accent: "#CFD8FF", secondary: "#82B1FF", glow: 0.45, edge: .gradient, brightness: 0.5, animation: .crystalGrid, eq: "instrumental_natural", background: .deepSpace)
    public static let studioMonoBlue = ThemePreset(id: "studio_mono_blue", name: "Studio Mono Blue", accent: "#40C4FF", secondary: "#B0BEC5", glow: 0.25, edge: .off, thickness: 0, brightness: 0, animation: .eqBarMirage, eq: "podcast_voice", background: .deepSpace, mode: .dark)
    public static let nocternalDefault = ThemePreset(id: "nocternal_default", name: "Nocternal Default", accent: "#00F0FF", secondary: "#FF00E5", glow: 0.8, edge: .musicReactive, animation: .pulseWaveSpectrum, eq: "flat", background: .deepSpace)
    public static let all: [ThemePreset] = [sacredGoldAura, emeraldTranquility, moonlitCyanDrift, royalPurpleGold, electricBluePulse, violetHyperspace, cyberRedPulse, bluePurpleGalaxy, softPinkGlow, aquaDrift, deepSpaceIndigo, voltLimeSurge, laserFocusTeal, roseNeonHeart, rainbowRave, sunriseAmber, silverStrings, studioMonoBlue, nocternalDefault]
    public static func byId(_ id: String) -> ThemePreset { all.first { $0.id == id } ?? nocternalDefault }
}
