#!/usr/bin/env bash
# Builds the engine for the browser demo:
#   djnexus.wasm    WebAssembly build of the C++ engine
#   djnexus-asm.js  the same code converted to plain JavaScript (wasm2js), used
#                   only where WebAssembly is unavailable
# Needs clang >= 16 with the wasm32-wasi sysroot and libc++, plus binaryen
# (Ubuntu: apt install clang lld wasi-libc libc++-18-dev-wasm32 libclang-rt-18-dev-wasm32 binaryen).
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=${1:-web}
mkdir -p "$OUT"
CXX=${CXX:-clang++}
SOURCES=(src/core/track.cpp src/core/stretcher.cpp src/core/deck.cpp src/core/channel.cpp
         src/core/recorder.cpp src/core/engine.cpp src/core/fx.cpp src/core/sampler.cpp src/core/colorfx.cpp src/core/macro.cpp src/capi.cpp src/decode/decoder_none.cpp
         src/midi/midi_mapping.cpp src/midi/midi_controller.cpp src/midi/midi_capi.cpp src/midi/midi_ports_none.cpp
         src/hosts/host_none.cpp src/web/djnexus_web.cpp)
# Export exactly the public C API (plus the web helpers, which export themselves).
EXPORTS=()
for fn in $(grep -o 'djn_[a-z_]*(' include/djnexus/djnexus.h | tr -d '(' | sort -u); do
  EXPORTS+=("-Wl,--export-if-defined=$fn")
done
"$CXX" --target=wasm32-wasi -std=c++17 -O3 -DNDEBUG -DDJN_NO_THREADS -fno-exceptions \
  -fvisibility=hidden -Iinclude -Isrc -Isrc/core "${SOURCES[@]}" \
  -nostartfiles -Wl,--no-entry -Wl,--export=__wasm_call_ctors "${EXPORTS[@]}" \
  -Wl,--strip-all -Wl,-z,stack-size=1048576 -o "$OUT/djnexus.wasm"
wasm-opt -O3 "$OUT/djnexus.wasm" -o "$OUT/djnexus.wasm"

# Plain-JS fallback: turn wasm2js's ES module into a classic script that
# defines globalThis.DJNexusAsm(env) -> exports, loadable in a page or worklet.
wasm2js "$OUT/djnexus.wasm" -O3 -o "$OUT/djnexus-asm.tmp.js"
python3 - "$OUT/djnexus-asm.tmp.js" "$OUT/djnexus-asm.js" <<'PY'
import re, sys
src = open(sys.argv[1]).read()
src = re.sub(r"^import .*$", "", src, flags=re.M)
src = src[: src.index("var retasmFunc")]
out = ("// Generated by web/build.sh from djnexus.wasm (wasm2js). Do not edit.\n"
       "(function () {\n" + src + "\nglobalThis.DJNexusAsm = asmFunc;\n})();\n")
open(sys.argv[2], "w").write(out)
PY
rm "$OUT/djnexus-asm.tmp.js"
ls -la "$OUT"/djnexus.wasm "$OUT"/djnexus-asm.js
